### ISSUE TITLE
Remove ClaimList, ClaimGroup, ClaimGroupSet?

### ISSUE THREAD

**Issue by lucaswerkmeister** [wmde/WikibaseDataModelJavaScript#76]
I don’t know their history, but as far as I can tell, `ClaimList`, `ClaimGroup` and `ClaimGroupSet` are currently unused, except that Wikibase Serialization JavaScript knows how to (de)serialize them. Perhaps they can be removed?

[Bug: T172916](https://phabricator.wikimedia.org/T172916)

**Comment by thiemowmde** [comment]
Fixed via:
* https://github.com/wmde/WikibaseSerializationJavaScript/pull/46
* https://github.com/wmde/WikibaseDataModelJavaScript/pull/80
