### ISSUE TITLE
 Readme is not understandable

### ISSUE THREAD

**Issue by jdittrich** [wmde/WikibaseDataModelJavaScript#83]
*same issue for other package is also at https://github.com/wmde/DataValuesJavaScript/issues/130*

**Story:** As a programmer (also one internal to the org) I want to understand what this javascript package does.

**Problem:** 
> It contains various JavaScript related to the DataValues library.

Does not tell anything about what it does and how it could be used . 

**Suggestion:** 

* Provide context: *This can be used with [other code/product]  for [goal]*
* Provide reason: *We created this to [goal]*
* Provide use: *If you want to use the library…*
* Provide coding standards: *We follow… please use the .jshint file in the … folder.*

**Helpful:**

*  [writing better readmes](https://opensource.com/open-organization/17/10/readme-maturity-model)

**Comment by thiemowmde** [comment]
It looks like you confused the two libraries. Neither "various" nor "DataValues" is in this library's readme. It says "JavaScript implementation of the Data Model", even with links. It's not that this can't be improved, but it's not that horrible as the other one.

**Comment by thiemowmde** [comment]
@jdittrich, can you please have a quick look at 3eeb6815c405ff5026ffa5384da44c603f1ed451 and close this issue if you think what I did there it good enough for now?

**Comment by jdittrich** [comment]
Much better, thanks! 

> It looks like you confused the two libraries
…indeed, you are right. Sorry for lazily copypasting.
